# Generated by Django 4.1.2 on 2022-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estiamflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='nbreepisode',
            field=models.IntegerField(verbose_name=int),
        ),
    ]
